root: true
plugins:
  - prettier
  - markdown

extends:
  - standard
  - prettier

rules:
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true
      trailingComma: es5
  require-jsdoc: warn
  valid-jsdoc: error
  spaced-comment:
    - error
    - always
    - exceptions:
        - /
        - '-'
      markers:
        - /
