root: true
plugins:
  - prettier
  - markdown

  - eslint-plugin

extends:
  - standard
  - prettier
  - plugin:eslint-plugin/recommended

rules:
  prettier/prettier:
    - error
    - semi: false
      singleQuote: true
      trailingComma: es5

  require-jsdoc: warn
  valid-jsdoc: error
  spaced-comment:
    - error
    - always
    - exceptions:
        - /
        - '-'
      markers:
        - /

  eslint-plugin/test-case-shorthand-strings:
    - error
    - consistent-as-needed
  eslint-plugin/test-case-property-ordering: error
  eslint-plugin/prefer-placeholders: error
  eslint-plugin/prefer-output-null: error
  eslint-plugin/no-deprecated-context-methods: error
  eslint-plugin/consistent-output: error
